### ISSUE TITLE
Thoughts on using .sublime-color-theme instead of .tmTheme?

### ISSUE THREAD

**Issue by aidenfoxivey** [dkter/st4_high_contrast_light#1]
I don't have a hard preference on it, but it might be more modern to use the .sublime-color-theme version of this. I can do a PR to add it if desired.

**Comment by aidenfoxivey** [comment]
https://gist.github.com/aidenfoxivey/42149216b5a996df1881131a1e4d102c

**Comment by dkter** [comment]
oh interesting, yeah sure I'd accept a PR

**Comment by aidenfoxivey** [comment]
I’ll send a patch shortly!
